-- MySQL Script generated by MySQL Workbench
-- Fri Mar 13 14:58:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_proj
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_proj
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_proj` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_proj` ;

-- -----------------------------------------------------
-- Table `db_proj`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_proj`.`customer` (
  `custFName` VARCHAR(45) NOT NULL,
  `custLName` VARCHAR(45) NOT NULL,
  `address` VARCHAR(500) NULL DEFAULT NULL,
  `balance` DECIMAL(10,2) UNSIGNED ZEROFILL NULL DEFAULT '00000000.00',
  `pwd` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_proj`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_proj`.`book` (
  `bookID` INT(11) NOT NULL AUTO_INCREMENT,
  `bookName` VARCHAR(100) NOT NULL,
  `author` VARCHAR(200) NULL DEFAULT NULL,
  `bookPrice` DECIMAL(10,2) NULL DEFAULT NULL,
  `fk_book_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`bookID`),
  INDEX `fk_book_username_idx` (`fk_book_username` ASC) VISIBLE,
  CONSTRAINT `fk_book_username`
    FOREIGN KEY (`fk_book_username`)
    REFERENCES `db_proj`.`customer` (`username`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_proj`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_proj`.`category` (
  `fk_cat_bookID` INT(11) NOT NULL,
  `numberAvailable` INT(11) NOT NULL,
  `fk_cat_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fk_cat_bookID`),
  INDEX `fk_cat_username_idx` (`fk_cat_username` ASC) VISIBLE,
  CONSTRAINT `fk_cat_bookID`
    FOREIGN KEY (`fk_cat_bookID`)
    REFERENCES `db_proj`.`book` (`bookID`),
  CONSTRAINT `fk_cat_username`
    FOREIGN KEY (`fk_cat_username`)
    REFERENCES `db_proj`.`customer` (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_proj`.`paymethod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_proj`.`paymethod` (
  `paymethodID` INT(11) NOT NULL AUTO_INCREMENT,
  `paymentName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`paymethodID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_proj`.`orderlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_proj`.`orderlist` (
  `orderID` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_payID` INT(11) NOT NULL,
  `fk_bookID` INT(11) NOT NULL,
  `date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `shipping_status` TINYINT(4) NULL DEFAULT '0',
  `fk_buyer_username` VARCHAR(45) NOT NULL,
  `fk_seller_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`orderID`),
  INDEX `bookID_idx` (`fk_bookID` ASC) VISIBLE,
  INDEX `fk_payID_idx` (`fk_payID` ASC) VISIBLE,
  INDEX `fk_cat_username_idx` (`fk_buyer_username` ASC) VISIBLE,
  INDEX `fk_seller_username_idx` (`fk_seller_username` ASC) VISIBLE,
  CONSTRAINT `fk_bookID`
    FOREIGN KEY (`fk_bookID`)
    REFERENCES `db_proj`.`book` (`bookID`),
  CONSTRAINT `fk_buyer_username`
    FOREIGN KEY (`fk_buyer_username`)
    REFERENCES `db_proj`.`customer` (`username`),
  CONSTRAINT `fk_payID`
    FOREIGN KEY (`fk_payID`)
    REFERENCES `db_proj`.`paymethod` (`paymethodID`),
  CONSTRAINT `fk_seller_username`
    FOREIGN KEY (`fk_seller_username`)
    REFERENCES `db_proj`.`customer` (`username`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
